// Generated by build_robot.py from robot.json. Units: mm.
// Prototype: measure shaft position, horn and fasteners before printing.
sl = 55.8;
sw = 20.3;
sh = 40.6;
shaft_offset = 14.0;
bl = 136.0;
bw = 108.0;
plate = 3.0;
hx = 48.0;
hy = 36.0;
reach = 45.0;
rise = 26.0;
leg_length = 90.0;
stance = 60.0;
foot_radius = 8.0;

// Select assembly, deck, carrier, leg, or foot; assembly includes servo envelopes.
part = "assembly";
$fn = 48;

module slot(length, width, height) {
    hull() for (x = [-1, 1]) translate([x*(length-width)/2, 0, 0])
        cylinder(d=width, h=height, center=true);
}
module rounded_plate(length, width, height, radius=5) {
    hull() for (x=[-1,1], y=[-1,1])
        translate([x*(length/2-radius), y*(width/2-radius), 0])
            cylinder(r=radius, h=height, center=true);
}
module deck() {
    difference() {
        translate([0,0,-plate/2]) rounded_plate(bl,bw,plate);
        for (front=[-1,1], side=[-1,1]) {
            // Shaft/horn access hole. Hip servo is strapped against deck underside.
            translate([front*hx,side*hy,-plate/2]) cylinder(d=18,h=plate+2,center=true);
            for (x=[-1,1], y=[-1,1])
                translate([front*(hx-shaft_offset)+x*sl/4,
                           side*hy+y*(sw/2+3),-plate/2])
                    slot(6,2.5,plate+2);
        }
        // Battery straps and controller cable access.
        for (x=[-24,24], y=[-22,22]) translate([x,y,-plate/2]) slot(12,3,plate+2);
        translate([0,0,-plate/2]) slot(20,8,plate+2);
    }
}
module carrier() {
    tray_x = reach-shaft_offset;
    tray_y = -sh/2-6;
    bottom = rise-sw/2-3;
    difference() {
        union() {
            translate([0,0,3.5]) cylinder(r=10,h=3,center=true);
            translate([0,0,(rise+4)/2]) cylinder(r=6,h=rise-4,center=true);
            translate([reach/2,-5,rise]) cube([reach+18,6,6],center=true);
            translate([tray_x,tray_y,bottom+1.5]) cube([sl+4,sh+4,3],center=true);
            // Front wall joins cradle, horn bridge, and base; rear wall retains servo.
            for (y=[-4.5,-sh-7.5]) translate([tray_x,y,rise-1.5])
                cube([sl+4,3,sw+3],center=true);
        }
        // Horn centre access and two adjustable attachment slots.
        translate([0,0,rise/2]) cylinder(d=3.2,h=rise+12,center=true);
        for (x=[-7,7]) translate([x,0,3.5]) slot(5,2.6,5);
        // Clearance around horizontal lift shaft.
        translate([reach,-4.5,rise]) rotate([90,0,0]) cylinder(d=14,h=14,center=true);
        // Two strap passages through the carrier floor.
        for (x=[-sl/4,sl/4]) translate([tray_x+x,tray_y,bottom+1.5])
            cube([3,sh-4,5],center=true);
    }
}
module leg() {
    difference() {
        hull() for (x=[0,leg_length]) translate([x,4,0])
            rotate([90,0,0]) cylinder(r=x==0 ? 10 : 5,h=4,center=true);
        translate([0,4,0]) rotate([90,0,0]) cylinder(d=3.2,h=6,center=true);
        for (x=[-7,7]) translate([x,4,0]) rotate([90,0,0]) slot(5,2.6,6);
        translate([leg_length,4,0]) rotate([90,0,0]) cylinder(d=3.2,h=6,center=true);
    }
}
module foot() {
    // Flexible-material cap; slit fits the flat leg tip. Fit must be tested.
    difference() {
        sphere(r=foot_radius);
        translate([-1.5,0,0]) cube([2*foot_radius-1,4.4,10.4],center=true);
        rotate([90,0,0]) cylinder(d=3.2,h=2*foot_radius+2,center=true);
    }
}
module assembly() {
    color([0.04,0.63,0.65]) deck();
    for (front=[-1,1], side=[-1,1]) {
        color([0.13,0.15,0.18])
            translate([front*(hx-shaft_offset),side*hy,-plate-sh/2])
                cube([sl,sw,sh],center=true);
        translate([front*hx,side*hy,0]) rotate([0,0,atan2(side,front)]) {
            color([0.04,0.63,0.65]) carrier();
            color([0.13,0.15,0.18]) translate([reach-shaft_offset,-sh/2-6,rise])
                cube([sl,sh,sw],center=true);
            translate([reach,0,rise]) rotate([0,stance,0]) {
                color([0.93,0.68,0.25]) leg();
                color([0.12,0.14,0.17]) translate([leg_length,4,0]) foot();
            }
        }
    }
}
if (part=="assembly") assembly();
else if (part=="deck") translate([0,0,plate]) deck();
else if (part=="carrier") translate([0,0,-2]) carrier();
else if (part=="leg") translate([0,0,-2]) rotate([90,0,0]) leg();
else if (part=="foot") translate([0,0,foot_radius]) foot();
else assert(false,"Unknown part selection");
